name: Deploy JSP App to VPS via DockerHub

on:
  push:
    branches: [ "deploy" ]

#  pull_request:
#    branches: [ "deploy" ]

env:
  IMAGE_NAME: tqhung/modern-home:0.1


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build WAR with Maven
        run: mvn clean package
        working-directory: ./backend

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME .
        working-directory: ./backend

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: docker push $IMAGE_NAME

      - name: Deploy on VPS
        run: |
          sudo apt-get update && sudo apt-get install -y sshpass
          sshpass -p "${{ secrets.VPS_PASSWORD }}" ssh -o StrictHostKeyChecking=no root@${{ secrets.VPS_HOST }} "
            IMAGE_NAME=${{ env.IMAGE_NAME }}
            docker pull  $IMAGE_NAME &&
            docker stop modern-home || true &&
            docker rm modern-home || true &&
          
            docker run -d --name modern-home -p 8000:8080 \
              -e GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} \
              -e GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} \
              -e FACEBOOK_APP_ID=${{ secrets.FACEBOOK_APP_ID }} \
              -e FACEBOOK_APP_SECRET=${{ secrets.FACEBOOK_APP_SECRET }} \
              -e RECAPTCHA_SECRET_KEY=${{ secrets.RECAPTCHA_SECRET_KEY }} \
              $IMAGE_NAME
          "
